# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vallalatok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephely',
            name='KTJ',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='It must have 9 digits. (Only digits).', regex='^\\d{9}$')], verbose_name='Környezetvédelmi Területi Jel'),
        ),
        migrations.AlterField(
            model_name='termelovallalat',
            name='KUJ',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='It must have 9 digits. (Only digits).', regex='^\\d{9}$')], verbose_name='Környezetvédelmi Ügyfél Jel'),
        ),
    ]
