# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vallalatok', '0002_auto_20170507_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vezeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=120)),
                ('beosztas', models.CharField(max_length=150)),
            ],
        ),
    ]
